### ISSUE TITLE
UI - Home Page: Nav-bar

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#113]
Update Nav-bar

The nav-bar should be updated to include a Help section. All button should have rounded corners of at least 5px. All nav-bar links and buttons should zoom when hovering. 

![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/c4987bf9-7bde-4734-af89-b1bdf2024faf)

Tasks:

- [x] Include Help link
- [x] Hutton rounding of 5px
- [x] Hover color change and Zoom effect

Help button:

- [x] Should link to the user manual

**Comment by Jeremy-Prior** [comment]
The help link is added to the top of the page and the buttons that are there are rounded. The nav bar buttons change colour when hovered on but do not zoom, and the `Help` button currently doesn't link to anywhere.

[issue113_1.webm](https://github.com/kartoza/SAEOSS-Portal/assets/100694811/8a15928a-6470-40aa-8417-e17316f5a674)
