### ISSUE TITLE
UI - Home: Implement video background

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#115]
The client would like to implement a video on the home page, and no longer want the static page. Video to be implemented is still do be confirmed.  

![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/1684f188-9d52-49d7-a9a7-5c39fbf3bb01)

The text and buttons should be visible and accessible above the image. 

Tasks:
- [x]  Implement video as background 
- [x]  Links should be visible and accessible over (on top of) the video
- [ ]  Confirm which video to use.

**Comment by zamuzakki** [comment]
@EliVolsch @voogt I have implemented video background. It uses YouTube embed feature, and some layout adjustment. Hence, the final video will need to be uploaded to YouTube (playlist is also supported).

This is how it looks.
[Kazam_screencast_00021-new.webm](https://github.com/kartoza/SAEOSS-Portal/assets/7352963/f88aeb3b-38f8-40ea-9b20-bcd064387a19)
