### ISSUE TITLE
UI - Social media Links

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#117]
The client would like a floating pane available on the middle left side of the screen which links to their social media platforms. 

Tasks:
- [x]  Confirm social media links
- [x] Implement floating pane
- [x] Link social media

**Comment by voogt** [comment]
![Image](https://github.com/kartoza/SAEOSS-Portal/assets/47378310/5eb4d67f-4236-4d9e-ace5-7678a6a07a5c)

floating pane is created. 
Waiting for links to social media to add

**Comment by voogt** [comment]
added social media links to facebook, linkedin, youtube and twitter

**Comment by Indiphile** [comment]
https://www.linkedin.com/in/south-african-national-space-agency-6a8b19a9/?originalSubdomain=za
