### ISSUE TITLE
UI Map update

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#122]
The client wants to implement two new base map resources. The client wants to implement [Pioneer](https://www.thunderforest.com/maps/pioneer/) and [Neighborhood](https://www.thunderforest.com/maps/neighbourhood/) from [thunderforest.com](https://www.thunderforest.com/) maps. The service has a free plan which limits users to 150 000 tile requests per month, but after that additional costs do apply. 

Risk:
- Additional costs per month after 150 000 tile requests.

Solution:
- Limit / Disable requests to avoid additional costs

**Comment by zamuzakki** [comment]
I have added Neighborhood and Pioneer as basemaps.
![basemaps-compressed](https://github.com/kartoza/SAEOSS-Portal/assets/7352963/8e373b75-cbd2-4153-b52b-0d2599b1bc20)
