### ISSUE TITLE
Buttons on Login Page overrun border

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/SAEOSS-Portal#129]
If a user decides to work in a split screen mode (i.e. two windows next to each other), or changes the aspect ratio of the web browser sufficiently, the buttons on the Login page overrun the border surrounding them

![issue129_1](https://github.com/kartoza/SAEOSS-Portal/assets/100694811/bdacd2a5-2feb-46ca-801c-714984e67504)

Is it possible to shrink the white space to the left of the blocks to keep the buttons within the border?

**Comment by zamuzakki** [comment]
This issue has been fixed in https://github.com/kartoza/SAEOSS-Portal/pull/135
