### ISSUE TITLE
Update UI as mockup 

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#14]
Work on the UI as https://www.figma.com/file/JHNNwfMCKvLczAcuOiu1NB/SAEOSS?node-id=503-714&t=ERFuZv3YlPv7wNxy-0
(The model has not yet been approved.)

**Comment by EliVolsch** [comment]
Re branding Of the platform will be implemented

**Comment by voogt** [comment]
- related to ticket #61
