### ISSUE TITLE
Viewing usage statistics produces error

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#140]
When viewing the usage statistics the following error is produced 
![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/5e72a948-5136-4d18-99dc-a0899ffc1ae3)
![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/dc003089-a5c6-4044-ac1b-51e3c3ed7574)
 
It would appear that this affect the entire platform and it becomes unusable. Can we deactivate this feature until the issue can be debugged

**Comment by zamuzakki** [comment]
@EliVolsch @voogt I've made PR to hide the Usage Statistics menu: https://github.com/kartoza/SAEOSS-Portal/pull/141
![image](https://github.com/kartoza/SAEOSS-Portal/assets/7352963/47457fb8-34e3-4a7c-9b73-1ae55bb84aa2)

**Comment by zamuzakki** [comment]
I've made fix to Usage Statistic page.
[Kazam_screencast_00025.webm](https://github.com/kartoza/SAEOSS-Portal/assets/7352963/015d1633-8a17-4b84-9fe2-623439310a66)
