### ISSUE TITLE
Add carousel to home page

### ISSUE THREAD

**Issue by voogt** [kartoza/SAEOSS-Portal#143]
![image](https://github.com/kartoza/SAEOSS-Portal/assets/47378310/10ededb0-0ade-40d5-a5d6-4c80fed66398)

**Comment by zamuzakki** [comment]
I have implemented carousel:
[Kazam_screencast_00024.webm](https://github.com/kartoza/SAEOSS-Portal/assets/7352963/b0067a3d-e71f-448f-930c-8be15f697d0d)

**Comment by voogt** [comment]
awaiting images to replace placeholder in carousel
