### ISSUE TITLE
Failed to run Create STAC Dataset command

### ISSUE THREAD

**Issue by zamuzakki** [kartoza/SAEOSS-Portal#147]
When running Create STAC Dataset e.g.
`docker exec -ti saeoss_ckan-web_1 poetry run ckan saeoss stac create-stac-dataset --url https://explorer.digitalearth.africa/stac --max=1`

It gets error like
- ckan.logic.ValidationError: None - {'lineage_statement': ['Missing value']}
- 2023-09-27 03:08:23,379 ERROR [ckan.lib.search.index] 'DEAfrica_data0396e949-640d-5ffa-8848-42f3732298d0': 'dataset_reference_date' value of [{'reference': '2022-1-5', 'reference_date_type': 1}] is not a valid date
2023-09-27 03:08:23,379 ERROR [ckan.lib.search.index] 'DEAfrica_data0396e949-640d-5ffa-8848-42f3732298d0': 'extras_metadata_date' value of 'metadata' is not a valid date
2023-09-27 03:08:23,379 ERROR [ckan.lib.search.index] 'DEAfrica_data0396e949-640d-5ffa-8848-42f3732298d0': 'metadata_date' value of 'metadata' is not a valid date

We (or I) need to talk to anyone involved in EMC (maybe @Fanevanjanahary ?), to understand to expected behavior of this command, whether it is running as expected in EMC, etc.

**Comment by zamuzakki** [comment]
@voogt We got 2 harvester.
- [HarvestingPlugin](https://github.com/kartoza/SAEOSS-Portal/blob/4bb21007bded753eec018e9b9f9236eda48bcff7/ckanext/saeoss/plugins/harvesting_plugin.py#L21), invoked from harvester page on browser, which harvest CSW link (maybe @Fanevanjanahary could confirm)
- [create_stac_dataset](https://github.com/kartoza/SAEOSS-Portal/blob/4bb21007bded753eec018e9b9f9236eda48bcff7/ckanext/saeoss/cli/commands.py#L1085), invoked from CLI.

I'm still trying to run and fix the issue with our Harvesting Plugin (the one I showed you on Friday), to know CKAN behavior when harvesting CSW. My assumption is, 1 CSW record will be saved as 1 dataset.

As for `create_stac_dataset`, the docstring added by Mohab says "and create datasets out of stack items". Regarding your question:
> Should data from harvest be saved as dataset or resource?
after checking https://csw-testing.emc.kartoza.com/collections/metadata:main/items and https://github.com/ckan/ckan/discussions/6364#discussioncomment-1282125, STAC item is saved as dataset. STAC Item's asset would be the resource.

**Comment by zamuzakki** [comment]
I've updated the STAC dataset creation command to:
- Correctly save bbox
- Save title and description
- Include STAC item as resource
- Include reference date and metadata date

![ckan-dataset-1](https://github.com/kartoza/SAEOSS-Portal/assets/7352963/4767f71a-2363-41d0-b990-a53dea956cd7)

**Comment by voogt** [comment]
@zamuzakki amazing thank you!
