### ISSUE TITLE
Update UI interface

### ISSUE THREAD

**Issue by voogt** [kartoza/SAEOSS-Portal#148]
- Update web interface to follow same design as search page with css

**Comment by voogt** [comment]
![image](https://github.com/kartoza/SAEOSS-Portal/assets/47378310/b562d626-dce4-4ac1-8314-2bbd4cd58eed)
![image](https://github.com/kartoza/SAEOSS-Portal/assets/47378310/1b04c244-d8ae-47cf-9fe3-239727d13d72)
![image](https://github.com/kartoza/SAEOSS-Portal/assets/47378310/ae10e9b4-42ea-4d69-b4bb-315e29c5ea3b)
![image](https://github.com/kartoza/SAEOSS-Portal/assets/47378310/fe9c868a-1a2c-453d-bad6-925cc97e8f71)
![image](https://github.com/kartoza/SAEOSS-Portal/assets/47378310/411ce66f-186a-4646-894e-1a183a2cd2fe)

**Comment by voogt** [comment]
Updated UI

**Comment by Indiphile** [comment]
The updated UI is perfect and clean.  We will have an internal discussion, focusing only on the images /videos to be used. The overall design is perfect. Thanks @voogt
