### ISSUE TITLE
Improve tool-tips to be more descriptive 

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#168]
Make improvements to tool-tips so they are more descriptive than they currently are
![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/5036e35b-ff33-43db-825c-3746e13843a6)

**Comment by zamuzakki** [comment]
Added tooltip for menubar and metadata search page.
[Kazam_screencast_00026.webm](https://github.com/kartoza/SAEOSS-Portal/assets/7352963/42085d46-5944-4a57-8811-12916cc51bae)
