### ISSUE TITLE
Add a map page

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#17]
This interface shall be capable of displaying footprints of datasets in polygon format in various common map projections. It shall do this on a publicly available base map layer (e.g., Google Maps, Bing Maps, Open Street Map) with zoom and pan functionality. The footprint of vector and raster datasets shall be displayed.

**Comment by Zintle95** [comment]
@Fanevanjanahary 

1.Display Footprints: The interface can show the footprints of datasets in polygon format.
2.Zoom and Pan Functionality: The interface enables users to zoom in and out for more detailed or broader views and offers pan functionality to explore different regions of the map.
3.Display Vector and Raster Footprints: It can handle both vector and raster datasets, accurately displaying their respective footprints on the map.
