### ISSUE TITLE
Improve map slide-pannels

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#175]
The map side need to be refined, and improved. There seem to be some floating icons without a clear description of what they are or represent. These icons should be improved and be described so users who are not familiar with the platform has an idea of what it does

![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/5a3e7e7d-d010-4dd2-a498-b35e43d33769) 
![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/80c36160-b986-4691-9a3e-8261cccc6bf1)

When the pannel is open, the icon does not invert to a close icon and is still misaligned or floating.
![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/90818a84-5c47-4b21-82b3-b2525a318466)

never show the user the inner workings of the system. These titles should be a common name and not the actual file name. This pannel does not make it clear that any of these items can be selected and displayed on the map.
![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/be682e0c-08c8-40f9-b11a-2ca240f4949f)

I suggest adding radio buttons which can be selected to add the record to the map.

**Comment by voogt** [comment]
@Eli the layer name is retrieved from the title object for a feature ex. https://explorer.digitalearth.africa/stac/search?collection=alos_palsar_mosaic

**Comment by Indiphile** [comment]
I don't think it's possible to change a tile title and also that title useful to some users. The radio button makes this map more user friendly. let's not close this ticket for now, I'm still waiting for the Data Tech team to provide us with more metadata ((SANS 1878-1)
