### ISSUE TITLE
Display records spatial extent on map

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#18]
We need an API to get the dataset from the database to display on the map page.

**Comment by Mohab25** [comment]
@Fanevanjanahary with CKAN the preferred workflow when pulling from DB is to make an action and setup the necessary access permissions (public vs private/organized datasets) ,
if you are busy with Templates assign me to this one - write up a bit to clarify what the action suppose to do

**Comment by EliVolsch** [comment]
We would like to seep polygons on being displayed on the map if available. If not available we should stick with bounding

**Comment by voogt** [comment]
Read features from api, switch between collection, show feature info on click

![Image](https://github.com/kartoza/SAEOSS-Portal/assets/47378310/cda46a0b-2c2b-4270-930d-3e11d8e51438)
