### ISSUE TITLE
Add different basemap

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#23]
Add base maps like Bing, Google Maps, and Topography to the map page.

![image](https://user-images.githubusercontent.com/12623986/234789987-1fa21a1d-78fe-4c78-8402-fd1e98f06fa2.png)

**Comment by EliVolsch** [comment]
Refer to issue #43 as the base map does not seem to display

**Comment by EliVolsch** [comment]
One proper graphic map and one proper satellite imagery
