### ISSUE TITLE
Harvesting catalogue csw

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/SAEOSS-Portal#36]
Harvest catalogue's csw to the portal

**Comment by Mohab25** [comment]
this is an old ticket, the functionality has been added to the system

**Comment by EliVolsch** [comment]
@voogt Can we clarify if this has been implemented

**Comment by EliVolsch** [comment]
need documentation ticket #155

**Comment by zamuzakki** [comment]
@voogt @EliVolsch While working on #38 , I saw this ticket and see that they're related.
After fixing the issue I found, I tried harvesting from EMC CSW, and it finished without issue. 
![Screenshot from 2023-10-03 07-06-57](https://github.com/kartoza/SAEOSS-Portal/assets/7352963/6b11b0d5-ab5a-40fc-a540-f3fd90dbb98b)
![Screenshot from 2023-10-03 07-07-21](https://github.com/kartoza/SAEOSS-Portal/assets/7352963/2c6eae7a-6269-4a8d-88e3-be3cf6ab600c)
![Screenshot from 2023-10-03 07-08-27](https://github.com/kartoza/SAEOSS-Portal/assets/7352963/2ed4a7ab-6d80-40e7-b9a1-67ed33e0dcb4)
