### ISSUE TITLE
STAC Harvesting

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/SAEOSS-Portal#37]

**Comment by LunaAsefaw** [comment]
Deadline: Before the next sprint meeting

**Comment by Mohab25** [comment]
this is an old ticket, the stac harvest functionality has been demo-ed and accepted by the client.

**Comment by EliVolsch** [comment]
@voogt Lets review this

**Comment by voogt** [comment]
Still researching about harvesting. Need a source to harvest from

**Comment by voogt** [comment]
Please look at ticket #147 for description of bug
