### ISSUE TITLE
Web Mapping Interface

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#43]
This interface shall be capable of displaying footprints of datasets in polygon format in various common map projections. It shall do this on a publicly available base map layer (e.g., Google Maps, Bing Maps, Open Street Map), with zoom and pan functionality. Footprint of vector and raster datasets shall be displayed. Where available in the correct map projection, thumbnails may be displayed on the map.

Justification or rationale: The user requires a visual map to interact with to understand the extent, location and number of spatial EO datasets available.
Verification requirements: Base map, zoom and pan functionality and footprint rendering visible reliably on mapping interface for multiple datasets under varying filters.

**Comment by EliVolsch** [comment]
Currently the map interface looks like this:
![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/b1dfb8a0-3657-4600-a1c2-f05fa26449bf)

It seems no base map is being displayed currently. This might point to a key issue
