### ISSUE TITLE
Search Interface

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#44]
The search/filtering interface shall allow the user to input a geographic search bounding box and a temporal search range, along with key value pairs denoting metadata fields and their required values to search the back-end metadata database. Common intrinsic attributes such as the data format and contributing organization will also be available as a search filter. Search results shall be displayed as footprints on the Web Mapping Interface and available for individual editing and viewing via the Metadata Editor Interface and Metadata Browser Interface respectively. Where available, thumbnail imagery shall be displayed with each metadata record.

Justification or rationale: Users require a graphical interface to input search filters and query a subset of the metadata records, which then must be graphically plotted on a map and listed to allow for inspection and interpretation.
Verification requirements: Expected search results list returned when filtered searches are queried alone or in combination.

**Comment by EliVolsch** [comment]
Already available with CKAN. Need customization.

**Comment by voogt** [comment]
Temporal search not working

**Comment by zamuzakki** [comment]
I found out that `reference_date` is not in SOLR documents. Hence we cannot query it, previously.
I added `reference_date` to the SOLR documents, in the PR.
