### ISSUE TITLE
Metadata Editor Interface

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#45]
This shall be a secured user facing interface allowing the user to add or modify metadata records to the Metadata Store and Search Database in the Data Back End. It shall be capable of working with XML, JSON and YAML format metadata files. The interface shall be secured using a username and password, which shall be pre-allocated by the system administrator.

Justification or rationale: Data curators require a human friendly graphical interface to make minor edits to single metadata records when browsing the metadata.
Verification requirements: Edits to existing metadata, in single or multiple fields, are persisted and restored across the various base metadata file formats.

**Comment by EliVolsch** [comment]
Already available with CKAN. Need customization.

**Comment by voogt** [comment]
Bug: Implement validation if resource is url

**Comment by gubuntu** [comment]
wasn't validation implemented in the EMC? If not, this is the sort of fix that must be pushed back upstream / shared with EMC

**Comment by voogt** [comment]
Hi @gubuntu this was extra functionality added for SAEOSS that does not exist in EMC. The editor allows you to edit resources uploaded to a dataset for minor edits
