### ISSUE TITLE
Metadata Browser Interface

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#46]
This interface shall allow the user a human-readable view of a selected metadata document regardless of underlying storage format, along with a very basic map showing the metadata spatial footprint and where available in the correct map projections, thumbnail imagery.

Justification or rationale: The user requires a casual graphical interface to explore individual metadata records to discover items of interest in terms of content, time and location.
Verification requirements: Metadata fields and characteristics faithfully reproduced in browser when compared to corresponding back-end database record.

**Comment by voogt** [comment]
What type of data will be uploaded? Will the resources have feature info that can be placed on a map (ex lat and lon need to be included or spatial box)

**Comment by voogt** [comment]
Update: Show tiff image if possible, otherwise default to thumbnail
