### ISSUE TITLE
Create Mockup

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#5]
Creating the UI design using https://www.figma.com

**Comment by Fanevanjanahary** [comment]
@SeffatChowdhury @Maite-Machipi @alamba84 please here is the mock up [(https://www.figma.com/file/JHNNwfMCKvLczAcuOiu1NB/SAEOSS?node-id=503%3A714&t=52mp0P2b8ASjhCZi-1](https://www.figma.com/file/JHNNwfMCKvLczAcuOiu1NB/SAEOSS?node-id=503%3A714&t=52mp0P2b8ASjhCZi-1)

cc @MarinaKartoza @Mohab25

**Comment by EliVolsch** [comment]
Initial mockup has been created and accepted


![Image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/addd6f0d-d3d0-407f-9bf1-713f5cf5b0ee)
