### ISSUE TITLE
Document: User Guide

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#55]
Create a publicly available instruction set shall be appropriate for the non-technical or external users of the system. It shall be linked on the SAEOSS portal landing page.

Expectation:
* Create a documentation set availible to public users.

**Comment by Indiphile** [comment]
The  user-guide is clear and it's easy to follow. We will close this ticket after changing the UI screenshots. After we have updated the UI  and organize few users from several organization to test the system(specifically the user-guide) then I will give you a feedback.
