### ISSUE TITLE
Document: Installation and Maintenance Guide

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#56]
The system shall be developed most likely by external contractors and the technical knowledge of the system needs to be captured and passed on to SANSA in documentation for post delivery maintenance, debugging and upgrades.

This technical knowledge base shall be used by SANSA for system deployment and maintenance and shall be updated on an ongoing basis. It shall describe the system architecture in medium level of detail and outline all software and hardware versions and configurations, as well as any common system tests and benchmarks, known issues and common pitfalls. It shall completely describe the deployment of the software on the appropriate hardware environment in a step-by-step fashion along with installation validation instructions.

Expectation:
* Create a documentation set followed by SANSA team to successfully deploy all software

**Comment by Indiphile** [comment]
- [Setting up dev env](https://kartoza.github.io/SAEOSS-Portal/developer/narrative/) : The `build.sh` script terminates the ubuntu terminal
- [build.sh scripts](https://github.com/kartoza/SAEOSS-Portal/blob/main/docker/build.sh) : I removed the errexit option on line 15. 
- The next error was permission, so I added `sudo` before `docker` on line 25,26 & 29
- Now I can't find a way to proceed from here :

![Image](https://github.com/kartoza/SAEOSS-Portal/assets/32433904/5a4384e2-3b04-424f-8f5f-7bb70056e2ca)

Please assist, @Fanevanjanahary  @EliVolsch

**Comment by gubuntu** [comment]
this documentation should be aligned with the DALRRD EMC documentation and any common content shared rather than being redeveloped

**Comment by voogt** [comment]
Hi @Indiphile please let me know what time suits you for a quick meeting that I can assist

**Comment by Indiphile** [comment]
Thanks @voogt. I'm free from 10 AM to 2PM tomorrow, you can schedule a meeting on your side. Thanks again @voogt

**Comment by Indiphile** [comment]
Hi @voogt, I was on study leave. Can we please reschedule our installation meeting.

**Comment by Indiphile** [comment]
`

![Image](https://github.com/kartoza/SAEOSS-Portal/assets/32433904/f6f6d912-cd46-4962-993e-da64123bfd45)

`

**Comment by Indiphile** [comment]
![Image](https://github.com/kartoza/SAEOSS-Portal/assets/32433904/1d220e66-9ec0-4f83-9767-00c6b461ea02)

Done
