### ISSUE TITLE
 Documentation: Developer mkdocstring email notification 

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#77]
Update mkdocstrings for email notification

**Comment by EliVolsch** [comment]
@Fanevanjanahary  can we update this ticket please

**Comment by EliVolsch** [comment]
This has been implemented and can be marked as complete



![Image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/c509d15a-ad5b-498a-9a51-4acc79b801e3)
