### ISSUE TITLE
Navigating to orgenisations from dashboard produces error

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#88]
When navigating from dashboard -> My organisations to a organisations. The following error is being produced. The same error is being displayed when navigating to organisations from the navigational pane.
![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/b29fe2d0-f5a8-4156-ba43-6dfcbeb371f6)
![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/a9024383-aea0-4523-8cde-4a23e6a101e2)

**Comment by voogt** [comment]
Hi @EliVolsch this error is resolved
