### ISSUE TITLE
Documentation: Update main page

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/SAEOSS-Portal#94]
Amend documentation and add information to the main/home page of the documentation page.

**Comment by EliVolsch** [comment]
Added SANSA logo and provided information about SANSA which is taken from the SANSA website. I provided links to the official website in the documentation
![image](https://github.com/kartoza/SAEOSS-Portal/assets/107027990/4a186797-7673-4b20-bc20-51921853d405)

**Comment by Indiphile** [comment]
SAEON logo added.
